### ISSUE TITLE
Stop running commands if they don't exist

### ISSUE THREAD

**Issue by msimos** [elastic/support-diagnostics#167]
I don't know why we expect every command to be there. Even the most basic bash shell will check to see if a directory or filename is there before doing something. The support diagnostic should do the same and not throw these exceptions. And throw some useful error messages like "netstat not found. Skipping.' For example:

Error processing system command:netstat
Error processing system command:ss
Error encountered running diagnostic. See logs for additional information.  Exiting application.
java.lang.NullPointerException: null
	at java.lang.String.replace(String.java:2240) ~[na:1.8.0_141]
	at com.elastic.support.diagnostics.commands.BaseSystemCallsCmd.executeCalls(BaseSystemCallsCmd.java:26) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.commands.SystemCallsCmd.execute(SystemCallsCmd.java:17) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:55) [support-diagnostics-5.13.jar:5.13]
Execution Error
java.lang.RuntimeException: Diagnostic runtime error
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:44) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:55) ~[support-diagnostics-5.13.jar:5.13]
Caused by: java.lang.NullPointerException: null
	at java.lang.String.replace(String.java:2240) ~[na:1.8.0_141]
	at com.elastic.support.diagnostics.commands.BaseSystemCallsCmd.executeCalls(BaseSystemCallsCmd.java:26) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.commands.SystemCallsCmd.execute(SystemCallsCmd.java:17) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-5.13.jar:5.13]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) ~[support-diagnostics-5.13.jar:5.13]
	... 1 common frames omitted

**Comment by archanid** [comment]
I think this particular stacktrace is because the pid has not been set on the context. It's trying to do 
```java
            cmdText = entry.getValue().replace("PID", context.getPid());
```

It could be that the command it's trying to run doesn't exist. I don't know the history/context of this code, but that to me just looks like we haven't set the pid, which is set to null when the constructor is invoked.

**Comment by nemonster** [comment]
I was going to put this one aside for a bit, since the assessment of what was wrong was pretty far off the mark. If you check this release, there were a large number of changes and refactoring. Which led to a few holes that exist when the utility wasn't run per instructions. That's one of the main reasons you'll have a null pid. Which generally indicates the host you're running on doesn't have a node in the cluster. Those have since been hopefully addressed in subsequent releases. Still waiting to see if any of the errors continue but it looks promising so far.

As far as checking for existence of a particular command: These calls are just simple one liners in the configuration. In fact, that simplicity has been a strength because it has set a fairly low bar for  others to contribute additions and changes. Most of what is in there were outside submissions. Which is more important, I think than being saved from a sporadic stack trace. Which will usually only occur when someone is using a less than standard OS install, in some container, or is not running with elevated permissions per instructions.

The program just iterates through each command, executing them one at a time and saving the output to file. If it errors out, it errors out and that gets saved as well. If it fails, it may have failed because a command wasn't there or it could have failed for another reason. But at this time I don't have any way of knowing that per command except via this mechanism. At some point when I refactor the logging, that may change since that should let me differentiate. But for now, lets keep in mind that it's a support tool, so if you're not used to seeing a Java Exception or stack trace here and there you're probably going to be really, really bummed out on a daily basis. A line saying "netstat not found" doesn't really convey that much extra significance, I think. Outcome is the same.  So I *may* do something about this eventually but it's not exactly a high priority at the moment.  

And keep in mind that the whole system command thing is pretty limited anyway. It runs on the host you're running the utility on. That's it. If that's not a node you have issues with you won't see much. Unless you manually run it on all nodes. One at a time. For bigger clusters that's kind of onerous, so again, I'm not sure you're buying anyone a significant amount of time or utility with this particular request. At least as submitted.
