### ISSUE TITLE
Running with help option should just print usage and gracefully exit

### ISSUE THREAD

**Issue by sandeepkanabar** [elastic/support-diagnostics#201]
If I run the diagnostic tool with `-?` or `--help` option, apart from printing usage, it throws an exception. 

```
[root@node00 support-diagnostics-6.3]# ./diagnostics.sh --help
Using /usr/java/jdk1.8.0_121/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
09:36:42 INFO  Validating inputs...
09:36:42 INFO  Creating temp directory.
09:36:42 INFO  Results will be written to: /root/support-diagnostics-6.3
09:36:42 INFO  Creating /root/support-diagnostics-6.3/diagnostics as temporary directory.
09:36:42 INFO  Created temp directory: /root/support-diagnostics-6.3/diagnostics
09:36:42 ERROR Testing
09:36:42 INFO  Configuring log file.
Usage: <main class> [options]
  Options:
    --accessLogs
       Use this option to collect access logs as well.
       Default: false
    --archivedLogs
       Get archived logs in addition to current ones if present - No value
       required, only the option.
       Default: false
    --bzip
       Set this option true to use bzip istead of gzip.
       Default: false
    -?, --help
       Help contents.
       Default: false
  * -h, --host
       Required field.  Hostname, IP Address, or localhost.  HTTP access must be
       enabled.
       Default: <empty string>
    -s, --ssl, --https
       Use SSL?  No value required, only the option.
       Default: false
    --interval
       Elapsed time in seconds between diagnostic runs when in repeating mode.
       Default: 30
    --keystore
       Keystore for client certificate.
    --keystorePass
       Keystore password for client certificate.
    --noLogs
       Use this option to suppress log collection.
       Default: false
    --noVerify
       Use this option to bypass hostname verification for certificate. This is
       inherently unsafe and NOT recommended.
       Default: false
    -o, --out, --output, --outputDir
       Fully qualified path to output directory or c for current working
       directory.
       Default: cwd
    -p, --password
       Password
    --port
       HTTP or HTTPS listening port. Defaults to 9200.
       Default: 9200
    --ptp
       Insecure plain text password - allows you to input the password as a
       plain text argument for scripts. WARNING: Exposes passwords in clear text.
       Inherently insecure.
       Default: <empty string>
    --reps
       Number of times to execute the diagnostic. Use to create multiple runs at
       timed intervals.
       Default: 1
    --scrub
       Set to true to use the scrub.yml dictionary to scrub logs and config
       files.  See README for more info.
       Default: false
    --threads
       Collect only hot threads.
       Default: false
    --type
       Diagnostic type to run. Enter standard, remote, logstash. Default is
       standard. Using remote will suppress retrieval of logs, configuration and system
       command info.
       Default: diagnostics
    -u, --user
       Username.

09:36:42 INFO  Writing diagnostic manifest.
09:36:43 INFO  Configuring REST endpoint.
09:36:43 INFO  Trying REST Endpoint.
09:36:43 ERROR Diagnostic query: nullfailed.
java.lang.IllegalArgumentException: Host may not be blank
	at org.apache.http.util.Args.notBlank(Args.java:74) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.cookie.CookieOrigin.<init>(CookieOrigin.java:51) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:141) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.2.jar:4.5.2]
	at com.elastic.support.util.RestModule.submitRequest(RestModule.java:59) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.util.RestModule.submitRequest(RestModule.java:45) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:26) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:32) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:36) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.Diagnostic.exec(Diagnostic.java:97) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:15) [support-diagnostics-6.3.jar:6.3]
09:36:43 ERROR Error retrieving Elasticsearch version  - unable to continue..  Please make sure the proper connection parameters were specified
java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:822) ~[jackson-core-2.5.3.jar:2.5.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578) ~[jackson-databind-2.5.3.jar:2.5.3]
	at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:28) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:32) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:36) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.Diagnostic.exec(Diagnostic.java:97) [support-diagnostics-6.3.jar:6.3]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:15) [support-diagnostics-6.3.jar:6.3]
09:36:43 INFO  Archiving diagnostic results.
09:36:43 INFO  Archive: /root/support-diagnostics-6.3/diagnostics-20180430-093643.tar.gz was created
09:36:43 INFO  Temp directory /root/support-diagnostics-6.3/diagnostics was deleted.
[root@node00 support-diagnostics-6.3]#
```

IMHO, when run with `-?` or `--help` option, it should just print usage and gracefully exit. Thoughts?

**Comment by nemonster** [comment]
Fixed in upcoming 6.4
