### ISSUE TITLE
6.4.1 does not honor --noVerify

### ISSUE THREAD

**Issue by inqueue** [elastic/support-diagnostics#208]
It looks like 6.4.1 does not like the `--noVerify` option. E.g.:

```
./diagnostics.sh --host $HOSTIP -u elastic -p --ssl --noVerify --type remote
```

Succeeds with diag version 6.3 and fails with SSL peer unverified with 6.4.1.

```
21:00:15.454 [main] INFO  com.elastic.support.diagnostics.Diagnostic - Configuring log file.
21:00:15.527 [main] INFO  com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd - Writing diagnostic manifest.
21:00:15.653 [main] INFO  com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd - Configuring REST endpoint.
21:00:15.881 [main] INFO  com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd - Checking for diagnostic version updates.
21:00:16.186 [main] INFO  com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd - Trying REST Endpoint.
21:00:16.266 [main] DIAG  com.elastic.support.util.RestExec - Error executing query.
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <໒( , ⊙ – ⊙ , )७> doesn't match any of the subject alternative names: [*.ip.es.io]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:467) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.5.jar:4.5.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar:4.5.5]
        at com.elastic.support.util.RestExec.exec(RestExec.java:91) [support-diagnostics-6.4.1.jar:6.4.1]
        at com.elastic.support.util.RestExec.execBasic(RestExec.java:57) [support-diagnostics-6.4.1.jar:6.4.1]
        at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:25) [support-diagnostics-6.4.1.jar:6.4.1]
        at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) [support-diagnostics-6.4.1.jar:6.4.1]
        at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:35) [support-diagnostics-6.4.1.jar:6.4.1]
        at com.elastic.support.diagnostics.Diagnostic.exec(Diagnostic.java:99) [support-diagnostics-6.4.1.jar:6.4.1]
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:16) [support-diagnostics-6.4.1.jar:6.4.1]
21:00:16.269 [main] ERROR com.elastic.support.util.RestExec - Failed to execute request: https://52.90.23.224:9200
21:00:16.269 [main] INFO  com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd - Error retrieving Elasticsearch version  - unable to continue..  Please make sure the proper connection parameters were specified
21:00:16.269 [main] INFO  com.elastic.support.diagnostics.Diagnostic - Archiving diagnostic results.
```

**Comment by nemonster** [comment]
Fixed in 6.4.2 release.
