### ISSUE TITLE
[7.0.x] diagnostics.sh RuntimeException: DiagnosticService runtime error 

### ISSUE THREAD

**Issue by inqueue** [elastic/support-diagnostics#267]
Support diagnostics against 7.0.0 GA is resulting in `java.lang.RuntimeException`. Attempted with support diagnostics 7.0.2 and 7.0.0. 

```
cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)
```

```
sudo ./diagnostics.sh --host localhost -u elastic -p --ssl --noVerify
Using /bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
15:59:07 INFO  Processing diagnosticInputs...
Password:
15:59:12 INFO  Creating temp directory: /home/user/support-diagnostics-7.0.2/diagnostics
15:59:12 INFO  Created temp directory: /home/user/support-diagnostics-7.0.2/diagnostics
15:59:12 INFO  Configuring log file.
15:59:12 INFO  Writing diagnostic manifest.
15:59:12 INFO  Getting Elasticsearch Version.
15:59:13 INFO  Log close complete.
Exception in thread "main" java.lang.RuntimeException: DiagnosticService runtime error
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:22)
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:57)
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31)
```

Help also results in error (this command works with v.6.4.4):
```
./diagnostics.sh --help
Using /bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
16:05:57 INFO  Processing diagnosticInputs...
Exception in thread "main" java.lang.NullPointerException
	at com.elastic.support.config.DiagnosticInputs.validate(DiagnosticInputs.java:248)
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:21)
```

**Comment by jguay** [comment]
--help also fails for me but I can generate a bundle from diag 7.0.2 against 7.0.0 cluster from the elasticsearch container or from my MacOS directly (elasticsearch running with self-signed certificate - same command as above)
JVM on my mac : 
```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
JVM on es 7.0.0 container :
```
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)
```

**Comment by inqueue** [comment]
diagnostics.log:
```
16:35:24.310 [main] INFO  com.elastic.support.diagnostics.commands.GenerateManifestCmd - Writing diagnostic manifest.
16:35:24.571 [main] INFO  com.elastic.support.diagnostics.commands.VersionCheckCmd - Getting Elasticsearch Version.
16:35:25.290 [main] DIAG  com.elastic.support.rest.RestClient - Unexpected Execution Error
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <localhost> doesn't match any of the subject alternative names: [127.0.0.1, some_host]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:475) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:405) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:364) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.7.jar:4.5.7]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.7.jar:4.5.7]
	at com.elastic.support.rest.RestClient.exec(RestClient.java:42) [support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.rest.RestClient.execQuery(RestClient.java:32) [support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.commands.VersionCheckCmd.execute(VersionCheckCmd.java:33) [support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) [support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:18) [support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:57) [support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31) [support-diagnostics-7.0.2.jar:7.0.2]
16:35:25.320 [main] DIAG  com.elastic.support.diagnostics.chain.DiagnosticChainExec - Error encountered running diagnostic. See logs for additional information.  Exiting application.
java.lang.RuntimeException: Unexpected exception
	at com.elastic.support.rest.RestClient.exec(RestClient.java:48) ~[support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.rest.RestClient.execQuery(RestClient.java:32) ~[support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.commands.VersionCheckCmd.execute(VersionCheckCmd.java:33) ~[support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:18) [support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:57) [support-diagnostics-7.0.2.jar:7.0.2]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31) [support-diagnostics-7.0.2.jar:7.0.2]
```

Using `--host 127.0.0.1` works. Expecting `--noVerify` to allow `localhost`.

**Comment by nemonster** [comment]
Fixed in above PR.
