### ISSUE TITLE
Error running diagnostic.sh 7.0.8 in container

### ISSUE THREAD

**Issue by bamb00** [elastic/support-diagnostics#292]
I'm getting exception running diagnostic.sh from inside the container.

I'm able to telnet to the same host and port 9200 is listening.  

     [root@security-master-0 support-diagnostics-7.0.8]# telnet 10.233.92.48 9200
     Trying 10.233.92.48...
     Connected to 10.233.92.48.
     Escape character is '^]'.
     Connection closed by foreign host.

     [root@security-master-0 diagnostics]# netstat -an | grep 9200
     tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN

     [elasticsearch@security-master-0 support-diagnostics-7.0.8]$ ./diagnostics.sh --host 10.233.92.48 -u elastic -p
     Using /usr/share/elasticsearch/jdk/bin/java as Java Runtime
     Using -Xms256m -Xmx2000m  for options.
     17:01:16 INFO  Processing diagnosticInputs...
     Password: 
     17:01:23 INFO  Creating temp directory: /usr/share/elasticsearch/support-diagnostics- 7.0.8/diagnostics
     Exception in thread "main" java.lang.NullPointerException
	at com.elastic.support.BaseService.closeLogs(BaseService.java:29)
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:87)
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31)

**Comment by nemonster** [comment]
I'm having a little trouble determining what you did here? Can you list the steps you performed with a bit more detail/granularity? 

Did you copy the diagnostic archive to the container and then run it from the the remote prompt?
If so, does that account have sufficient permissions to run the diagnostic? The displayed error has to do with the logging appender, but I suspect there's a deeper one. If there was a temp directory created then there should be a log with more extensive information in that. if you can put up a safely scrubbed version of that I can take a look.

Try running it from the host that is running the containers and pointing it to the published HTTP port for the node you wish to access with the --type remote option. And you can get docker stats for a particular container by providing the --dockerID. Check the readme for the example.

**Comment by bamb00** [comment]
@nemonster Hi Greg,

I installed openjdk 1.8.0, 

     openjdk version "1.8.0_212"
     OpenJDK Runtime Environment (build 1.8.0_212-b04)
     OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

then ran the diagnostic.sh and get the following error...

		# more remote-diagnostics/diagnostics.log 
		20:38:10.721 [main] INFO  com.elastic.support.diagnostics.commands.GenerateManifestCmd - Writing diagnostic manifest.
		20:38:10.905 [main] INFO  com.elastic.support.diagnostics.commands.VersionCheckCmd - Getting Elasticsearch Version.
		20:38:11.172 [main] DIAG  com.elastic.support.rest.RestClient - Unexpected Execution Error
		javax.net.ssl.SSLPeerUnverifiedException: Certificate for <192.168.27.5> doesn't match any of the subject alternative names: []
			at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:475) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:405) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:364) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.7.jar:4.5.7]
			at com.elastic.support.rest.RestClient.exec(RestClient.java:42) [support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.rest.RestClient.execQuery(RestClient.java:32) [support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.commands.VersionCheckCmd.execute(VersionCheckCmd.java:35) [support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) [support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:18) [support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:59) [support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31) [support-diagnostics-7.0.8.jar:7.0.8]
		20:38:11.177 [main] ERROR com.elastic.support.diagnostics.commands.VersionCheckCmd - Could not retrieve the Elasticsearch version - unable to continue.
		20:38:11.177 [main] DIAG  com.elastic.support.diagnostics.chain.DiagnosticChainExec - Error encountered running diagnostic. See logs for additional information.  Exiting application.
		java.lang.NullPointerException: null
			at com.elastic.support.diagnostics.commands.UserRoleCheckCmd.execute(UserRoleCheckCmd.java:36) ~[support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:18) [support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:59) [support-diagnostics-7.0.8.jar:7.0.8]
			at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31) [support-diagnostics-7.0.8.jar:7.0.8]

**Comment by bamb00** [comment]
@nemonster Hi Greg,

Installed the OpenJDK 1.8.0 also included the --noVerify in the command was able to get the diagnostic. 

Thanks.

**Comment by nemonster** [comment]
Issue was a combination of the IBM JDK and the hostname used not being in the cert. Will add more descriptive error message for authentication issues.
