### ISSUE TITLE
Sometimes local system calls don't run

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/support-diagnostics#294]
There is a condition under which the diag does not [identify](https://github.com/elastic/support-diagnostics/blob/5ef5570e9f3f0237809a63683251ec5679e7f2c5/src/main/java/com/elastic/support/diagnostics/commands/HostIdentifierCmd.java#L64-L87) that is running locally on a host machine.    

I'm not exactly sure of the conditions of the issue, however the cluster ran a diag with a hostname that connected and pulled down the diagnostic, but didn't recognize it as being the local environment:

```
11:37:03.191 [main] DIAG  com.elastic.support.diagnostics.commands.HostIdentifierCmd - pvmkf079.corp.sprint.com host was not found in the nodes output
11:37:03.191 [main] INFO  com.elastic.support.diagnostics.commands.CollectLogsCmd - Bypassing log collection.
11:37:03.191 [main] INFO  com.elastic.support.diagnostics.commands.SystemCallsCmd - The host this utility is running on could not be found in the cluster - Bypassing system calls
11:37:04.837 [main] INFO  com.elastic.support.diagnostics.commands.SystemDigestCmd - Finished querying SysInfo.
```

I was unsure what to do so I asked the customer to use the exposed IP address instead and it worked.

**Comment by nemonster** [comment]
I query the interface for available hostnames or IP addresses. If there's
not a hostname that matches the one they used I can't tell if they're
running on that host or not. I need that to get the location of the logs
and to verify that they're running on the host they say they are. If it's a
DNS entry only and doesn't match the hostname I won't find anything. In
some cases a DNS name might map to several servers so that's not the most
reliable indicator to use.

I don't know if this is worth addressing by anything other than some
additional cautions in the documentation though.

**Comment by radu-gheorghe** [comment]
I get a similar issue, on Ubuntu 18.04. I've tried with Elasticsearch 6.x and 7.x and get the same problem:
```14:59:51.252 [main] INFO  com.elastic.support.diagnostics.commands.CheckPlatformDetails - Checking the supplied hostname against the node information retrieved to verify location. This may take some time.
14:59:51.311 [main] ERROR com.elastic.support.diagnostics.commands.CheckPlatformDetails - Comparison did not result in an IP or Host match. [fe80:0:0:0:a00:27ff:fee0:1ba4%enp0s8, enp0s3, lo, 2a02:2f0a:410d:8200:a00:27ff:fee0:1ba4%enp0s8, ubuntu-bionic, enp0s8, 10.0.2.15, 192.168.1.105, 0:0:0:0:0:0:0:1%lo, ip6-localhost, fe80:0:0:0:62:7aff:fe79:f6ca%enp0s3] [ProcessProfile{isHttp=true, isDocker=false, currentMaster=false, name='ubuntu-bionic', id='bNnY-ZXlT-aNAx0Gb8DbIw', pid='24358', jvmPid='', logDir='/var/tmp/elasticsearch-7.8.0/logs', networkHost='', host='127.0.0.1', ip='127.0.0.1', httpPublishAddr='127.0.0.1', httpPort=9200, os='linuxOS', boundAddresses=[], javaPlatform=com.elastic.support.diagnostics.JavaPlatform@dffa30b}]
14:59:51.313 [main] ERROR com.elastic.support.diagnostics.commands.CheckPlatformDetails - Error: Could not find the target node.
14:59:51.313 [main] ERROR com.elastic.support.diagnostics.commands.CheckPlatformDetails - Error checking node metadata and deployment info.
java.lang.RuntimeException: Could not find the target node.
        at com.elastic.support.diagnostics.commands.CheckPlatformDetails.findTargetNode(CheckPlatformDetails.java:323) ~[support-diagnostics-8.1.1.jar:8.1.1]
        at com.elastic.support.diagnostics.commands.CheckPlatformDetails.findLocalTargetNode(CheckPlatformDetails.java:288) ~[support-diagnostics-8.1.1.jar:8.1.1]
        at com.elastic.support.diagnostics.commands.CheckPlatformDetails.execute(CheckPlatformDetails.java:149) [support-diagnostics-8.1.1.jar:8.1.1]
        at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:33) [support-diagnostics-8.1.1.jar:8.1.1]
        at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:68) [support-diagnostics-8.1.1.jar:8.1.1]
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:42) [support-diagnostics-8.1.1.jar:8.1.1]```

I'm not sure if it's a different issue @nemonster, maybe I should open a new one?

The thing that I don't understand is this part: `boundAddresses=[]`

For reference, I'm running diagnostics via `./diagnostics.sh --host localhost`

Would it be useful to have a flag to force running system calls? I'd love to submit such a PR if you give me a few pointers (I tried already once to patch DiagnosticChainExec and it didn't work).

**Comment by nemonster** [comment]
Will comment in that issue.
