### ISSUE TITLE
--skipLogs setting not recognized

### ISSUE THREAD

**Issue by jguay** [elastic/support-diagnostics#323]
According to [README](https://github.com/elastic/support-diagnostics#additional-options) : 
```
To suppress all log file collection use the --skipLogs option.
```

Running the following currently fails (diagnostics 7.1.1) when `--skipLogs` is mentioned
```
./diagnostics.sh --host localhost -u elastic -p --ssl --skipLogs
```

The error returned is
```
10:32:20 DIAG  Unanticipated error
com.beust.jcommander.ParameterException: Was passed main parameter '--skipLogs' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936) ~[jcommander-1.72.jar:?]
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:752) ~[jcommander-1.72.jar:?]
	at com.beust.jcommander.JCommander.parse(JCommander.java:340) ~[jcommander-1.72.jar:?]
	at com.beust.jcommander.JCommander.parse(JCommander.java:319) ~[jcommander-1.72.jar:?]
	at com.elastic.support.config.BaseInputs.parseInputs(BaseInputs.java:18) ~[support-diagnostics-7.1.1.jar:7.1.1]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:21) [support-diagnostics-7.1.1.jar:7.1.1]
```

**Comment by nemonster** [comment]
@jguay I removed this option a while back and missed the reference in the README. If you aren't going to collect logs on a node it probably doesn't make a great deal of sense to get the system calls either. And at that point you're just running remote mode. Or if it's a docker installation, and in that case it should detect that and bypass the logs anyway. I'll fix the README in the next release.

**Comment by jguay** [comment]
Thank you @nemonster for confirming it's a doc bug - basically we just wanted to ensure the logs did not get included and collecting remotely works just fine, feel free to close this issue
