### ISSUE TITLE
Manifest not being generated.(v7.1.3)

### ISSUE THREAD

**Issue by dharada** [elastic/support-diagnostics#343]
<h2>How to reproduce</h2>
We can reproduce the issue with this command.

```
sudo ./diagnostics.sh --host localhost --type logstash
```

https://github.com/elastic/support-diagnostics#logstash-examples

<h3>log</h3>

```
12:35:13.964 [main] INFO  com.elastic.support.diagnostics.commands.CheckDiagnosticVersion - Checking for diagnostic version updates.
12:35:13.965 [main] DIAG  com.elastic.support.diagnostics.commands.CheckDiagnosticVersion - java.lang.NullPointerException
12:35:13.965 [main] INFO  com.elastic.support.diagnostics.commands.CheckDiagnosticVersion - Issue encountered while checking diagnostic version for updates.
12:35:13.965 [main] INFO  com.elastic.support.diagnostics.commands.CheckDiagnosticVersion - Failed to get current diagnostic version from Github.
12:35:13.965 [main] INFO  com.elastic.support.diagnostics.commands.CheckDiagnosticVersion - If Github is not accessible from this environemnt current supported version cannot be confirmed.
12:35:13.967 [main] DIAG  com.elastic.support.diagnostics.commands.BaseQuery - Logstash Query error:
java.lang.NullPointerException: null
	at com.elastic.support.diagnostics.commands.RunLogstashQueries.execute(RunLogstashQueries.java:28) [support-diagnostics-7.1.3.jar:7.1.3]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:34) [support-diagnostics-7.1.3.jar:7.1.3]
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:56) [support-diagnostics-7.1.3.jar:7.1.3]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31) [support-diagnostics-7.1.3.jar:7.1.3]
12:35:13.973 [main] WARN  com.elastic.support.diagnostics.DiagnosticService - Error obtaining logstash output and/or process id - exiting. Check diagnostics.log in the archive file for more detail.

```

<h4>Note</h4>
 I could confirm it works with older version. (e.g v7.0.7)  (chose this old version for just quick.)
https://github.com/elastic/support-diagnostics/releases/download/7.0.7/support-diagnostics-7.0.7-dist.zip

**Comment by nemonster** [comment]
@dharada It's mainly due to an issue with manifest generation. Should be fixed in the 7.1.4 release that's up there now.
