### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by kvmuralidhar** [elastic/support-diagnostics#372]
Hi,

I am trying to gather diagnostics for a logstash instance and getting a null pointer exception.

./diagnostics.sh --host localhost --type logstash --port 9600

Here is the backtrace.
`Logstash Query error:
java.lang.NullPointerException: null
        at com.elastic.support.diagnostics.commands.RunLogstashQueries.execute(RunLogstashQueries.java:28) [support-diagnostics-7.1.5.jar:7.1.5]
        at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:35) [support-diagnostics-7.1.5.jar:7.1.5]
        at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:56) [support-diagnostics-7.1.5.jar:7.1.5]
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31) [support-diagnostics-7.1.5.jar:7.1.5]
`

Thanks
Murali

**Comment by nemonster** [comment]
For an immediate workaround rollback to the 7.1.1 version and just ignore the nag message when it says it's out of date. That should get you a diagnostic.

This is fixed in a new version that will be released in the next couple of weeks.

**Comment by kvmuralidhar** [comment]
Hi Greg,

Thank you :-).

Murali
