### ISSUE TITLE
Remote option is failing to connect

### ISSUE THREAD

**Issue by BobBlank12** [elastic/support-diagnostics#424]
Attempting to use a remote option for a logstash diag, diag tool is failing to connect:

```
./diagnostics.sh --host 192.168.2.250 --type logstash-remote --remoteUser elk --remotePass
```

```
13:49:33.148 [main] INFO  com.elastic.support.diagnostics.commands.CheckDiagnosticVersion - Checking for diagnostic version updates.
13:49:33.508 [main] DIAG  com.elastic.support.rest.RestClient - Host connection error.
org.apache.http.conn.HttpHostConnectException: Connect to 192.168.2.250:9600 [/192.168.2.250] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.10.jar:4.5.10]
	at com.elastic.support.rest.RestClient.execRequest(RestClient.java:71) [support-diagnostics-8.0.7.jar:8.0.7]
	at com.elastic.support.rest.RestClient.execGet(RestClient.java:66) [support-diagnostics-8.0.7.jar:8.0.7]
	at com.elastic.support.rest.RestClient.execQuery(RestClient.java:61) [support-diagnostics-8.0.7.jar:8.0.7]
	at com.elastic.support.diagnostics.commands.BaseQuery.execQueryList(BaseQuery.java:74) [support-diagnostics-8.0.7.jar:8.0.7]
	at com.elastic.support.diagnostics.commands.BaseQuery.runQueries(BaseQuery.java:32) [support-diagnostics-8.0.7.jar:8.0.7]
	at com.elastic.support.diagnostics.commands.RunLogstashQueries.execute(RunLogstashQueries.java:40) [support-diagnostics-8.0.7.jar:8.0.7]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:70) [support-diagnostics-8.0.7.jar:8.0.7]
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:61) [support-diagnostics-8.0.7.jar:8.0.7]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:43) [support-diagnostics-8.0.7.jar:8.0.7]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.10.jar:4.5.10]
	... 17 more
```

SSH with user/password is working to this remote server... anything else to check?

**Comment by nemonster** [comment]
That's an HTTP connection error. Check the logstash.yml to see if the http.host and/or http.port are set to something you can access remotely. By default Logstash binds to localhost and that's it. So the only incoming http requests it will accept will be from those made on that same host.

`
http.host: 0.0.0.0`
`port:9600`

Usually gets things working.

**Comment by inqueue** [comment]
It feels like the remote option should execute REST calls over ssh to localhost by default. Something like:

```
ssh user@logstash_host "curl localhost:9600"
```

It'd be neat if the diagnostic offered a `remoteHost` parameter that could serve as a remote gateway for remote calls. Then something like this might work:

```
./diagnostics.sh --host localhost --type logstash-remote --remoteUser elk --remotePass --remoteHost 192.168.2.250
```

The diagnostic would do all its data collection for localhost via 192.168.2.250, the host itself. `remoteHost` could also work with type `api` over ssh given the host has API port access to the target `host`.

**Comment by nemonster** [comment]
@inqueue I'm not convinced it's realistic to completely rewrite all the REST routines with the equivalent curl calls when if they've got an SSH login all they have do is shell in and run the utility. The remote mode is mainly just a convenience for those who have taken the extra time and effort to set up the REST interface. 

I'm considering putting in an option to just run remote system calls against a list of hosts to automate collection of those types of things though. If that were the case you could just add the curl versions to the existing system calls and they'd come along for the ride.
