### ISSUE TITLE
Configure Elasticsearch on kubernetes (GCP)  for OpenID Connect authentication

### ISSUE THREAD

**Issue by nababou** [elastic/support-diagnostics#435]
Hi everyone, 
I tried to configure authentication in kibana with OpenID Connect single sign-on, but I have some issue for configuring single sign-on to the Elastic Stack using OpenID Connect.
-version 7.2.1
-GKE GCP 
-CRD version is  0.8.1
Error: 
020-06-25T12:21:02.165082717Z uncaught exception in thread [main]
2020-06-25T12:21:02.166349446Z java.lang.IllegalArgumentException: unknown setting [node.xpack.security.authc.token.enabled] did you mean any of [xpack.security.authc.token.enabled, xpack.security.authc.api_key.enabled, xpack.security.authc.run_as.enabled]?
2020-06-25T12:21:02.16638131Z 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:532)
2020-06-25T12:21:02.166387669Z 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:477)
2020-06-25T12:21:02.166392645Z 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:448)
2020-06-25T12:21:02.166397483Z 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:419)
2020-06-25T12:21:02.166402907Z 	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:149)
2020-06-25T12:21:02.166408411Z 	at org.elasticsearch.node.Node.<init>(Node.java:356)
2020-06-25T12:21:02.166421078Z 	at org.elasticsearch.node.Node.<init>(Node.java:257)
2020-06-25T12:21:02.16644455Z 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221)
2020-06-25T12:21:02.166456128Z 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221)
2020-06-25T12:21:02.166466736Z 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
2020-06-25T12:21:02.166487135Z 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
2020-06-25T12:21:02.166491895Z 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
2020-06-25T12:21:02.166496427Z 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
2020-06-25T12:21:02.166500751Z 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
2020-06-25T12:21:02.166505451Z 	at org.elasticsearch.cli.Command.main(Command.java:90)
2020-06-25T12:21:02.166509905Z 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
2020-06-25T12:21:02.166514412Z 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)

[elasticsearch.txt](https://github.com/elastic/support-diagnostics/files/4832133/elasticsearch.txt)

Thank you for your help

**Comment by nemonster** [comment]
@nababou This repo is for issues and questions encountered when running the support diagnostic utility for Elasticsearch. That doesn't appear to have an apparent relationship to the text of the issue. If you're looking for general setup and configuration information [the online discussion groups](https://www.elastic.co/community/) would be the appropriate location.
