### ISSUE TITLE
[bug] scrubber fresh install fails to run

### ISSUE THREAD

**Issue by nerophon** [elastic/support-diagnostics#511]
The scrubber, part of a fresh download, consistently fails to run with error:
```
The system cannot find the file C:\support-diagnostics-8.1.4\lib\NUL.
Runtimes library does not exist - make sure you are running the archive with 'dist' in the name, not the one labeled: 'source'.
```

Here is more from the scrubber.log:

```
13:12:46.634 [main] INFO com.elastic.support.BaseService - Diagnostic logger reconfigured for inclusion into archive
13:12:46.634 [main] INFO com.elastic.support.scrub.ScrubService - Threadpool configured with 4 workers.
13:12:46.680 [main] ERROR com.elastic.support.scrub.ScrubService - Error occurred: 
java.lang.NullPointerException: null
at java.io.Reader.<init>(Reader.java:167) ~[?:?]
at java.io.InputStreamReader.<init>(InputStreamReader.java:113) ~[?:?]
at org.apache.commons.io.IOUtils.copy(IOUtils.java:2440) ~[commons-io-2.6.jar:2.6]
at org.apache.commons.io.IOUtils.toString(IOUtils.java:1084) ~[commons-io-2.6.jar:2.6]
at org.apache.commons.io.IOUtils.toString(IOUtils.java:1110) ~[commons-io-2.6.jar:2.6]
at com.elastic.support.scrub.ScrubService.getNodeInfoFromZip(ScrubService.java:156) ~[support-diagnostics-8.1.4.jar:8.1.4]
at com.elastic.support.scrub.ScrubService.exec(ScrubService.java:54) [support-diagnostics-8.1.4.jar:8.1.4]
at com.elastic.support.scrub.ScrubApp.main(ScrubApp.java:42) [support-diagnostics-8.1.4.jar:8.1.4]
13:12:46.696 [main] ERROR com.elastic.support.scrub.ScrubService - Issue encountered during scrub processing. Check diagnostics.log in the archive file for more detail..
13:12:46.696 [main] INFO com.elastic.support.BaseService - Closing loggers.
13:12:46.696 [main] INFO com.elastic.support.util.SystemUtils - Deleted directory: C:\Software\support-diagnostics-8.1.4\scrubbed-diagnostic-e7bbbc-2021-Jun-29--16_34_35.
```

We definitely downloaded the built package, not the source.
We checked the diagnostic utility, that works fine.
Environment details:
```
Virtual Machine
Java JDK 13.0.2
echo %java_home% C:\Program Files\Java\jdk-13.0.2\
Windows Server 2016
Version 1607
support diagnostic tool 8.1.4
No non default settings
```

**Comment by pickypg** [comment]
Can you have them try modifying the `scrub.bat` file and remove the `\NUL`, then retry? The `scrub.sh` does not have that and it seems wrong.

https://github.com/elastic/support-diagnostics/blob/8e12e21688f0fd4fd7b8d72c1e06ff33e7af9d3d/scripts/scrub.bat#L6

**Comment by jonny-mcc** [comment]
I also get the same errors but using the bash script rather than the bat file

```
 ./scrub.sh -i diagnostic-5e19d4-2021-Jul-26--17_40_55.zip

 Using /bin/java as Java Runtime. 
 Using -Xms8g -Xmx8g  for options.  
 2021-07-28 22:13:52,878 main ERROR Unable to locate appender "diag" for logger config "root"    
 Processing diagnosticInputs...   
 Using version: 8.1.4 of diagnostic-utiliy
 Deleted directory: /home/support-diagnostics-8.1.4/scrubbed-diagnostic-5e19d4-2021-Jul-26--17_40_55.
 Diagnostic logger reconfigured for inclusion into archive
 Threadpool configured with 2 workers.
 Issue encountered during scrub processing. Check diagnostics.log in the archive file for more detail.
 Closing loggers.
 Deleted directory: /home/support-diagnostics-8.1.4/scrubbed-diagnostic-5e19d4-2021-Jul-26--17_40_55.
```
Looking at `scrubber.log` yields
```
22:13:53.182 [main] INFO  com.elastic.support.BaseService - Diagnostic logger reconfigured for inclusion into archive
22:13:53.183 [main] INFO  com.elastic.support.scrub.ScrubService - Threadpool configured with 2 workers.
22:13:53.235 [main] ERROR com.elastic.support.scrub.ScrubService - Error occurred:
java.lang.NullPointerException: null
        at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_302]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:113) ~[?:1.8.0_302]
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2440) ~[commons-io-2.6.jar:2.6]
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:1084) ~[commons-io-2.6.jar:2.6]
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:1110) ~[commons-io-2.6.jar:2.6]
        at com.elastic.support.scrub.ScrubService.getNodeInfoFromZip(ScrubService.java:156) ~[support-diagnostics-8.1.4.jar:8.1.4]
        at com.elastic.support.scrub.ScrubService.exec(ScrubService.java:54) [support-diagnostics-8.1.4.jar:8.1.4]
        at com.elastic.support.scrub.ScrubApp.main(ScrubApp.java:42) [support-diagnostics-8.1.4.jar:8.1.4]
22:13:53.241 [main] ERROR com.elastic.support.scrub.ScrubService - Issue encountered during scrub processing. Check diagnostics.log in the archive file for more detail..
22:13:53.242 [main] INFO  com.elastic.support.BaseService - Closing loggers.
22:13:53.243 [main] INFO  com.elastic.support.util.SystemUtils - Deleted directory: /home/support-diagnostics-8.1.4/scrubbed-diagnostic-5e19d4-2021-Jul-26--17_40_55.
```

However, after unzipping the support bundle the scrubbing tool worked again


```
unzip diagnostic-5e19d4-2021-Jul-26--17_40_55.zip
./scrub.sh -i diagnostic-5e19d47efd1c400092c4a1db2b6b199c/
Using /bin/java as Java Runtime
Using -Xms8g -Xmx8g  for options.
2021-07-28 23:53:49,896 main ERROR Unable to locate appender "diag" for logger config "root"
Processing diagnosticInputs...
Using version: 8.1.4 of diagnostic-utiliy
Deleted directory: /home/support-diagnostics-8.1.4/scrubbed-.
Diagnostic logger reconfigured for inclusion into archive
Threadpool configured with 2 workers.
Processed entry: ml_stats.json
...
Processed entry: indices_stats.json
Archiving diagnostic results.
Archive: /home/support-diagnostics-8.1.4/scrubbed--20210728-235351.zip was created
Closing loggers.
Deleted directory: /home/support-diagnostics-8.1.4/scrubbed-.
```
[diagnostic-5e19d4-2021-Jul-26--17_40_55.zip](https://github.com/elastic/support-diagnostics/files/6897019/diagnostic-5e19d4-2021-Jul-26--17_40_55.zip)

```
Environment:
CentOS 8
Java 1.8.0.302
Support diagnostic tool 8.1.4
ECE 2.6.2

```
