### ISSUE TITLE
java.lang.RuntimeException: Host/Platform check error.  (when use --type logstash-api)

### ISSUE THREAD

**Issue by dharada** [elastic/support-diagnostics#583]
The following ERROR stacktrace is shown even if they use supported type (--type logstash-api).

```
[main] ERROR co.elastic.support.diagnostics.commands.BaseQuery - Logstash Query error:
java.lang.RuntimeException: Host/Platform check error.
        at co.elastic.support.diagnostics.commands.RunLogstashQueries.execute(RunLogstashQueries.java:106) [diagnostics-8.2.8.jar:8.2.8]
        at co.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:92) [diagnostics-8.2.8.jar:8.2.8]
        at co.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:86) [diagnostics-8.2.8.jar:8.2.8]
        at co.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:51) [diagnostics-8.2.8.jar:8.2.8]
```

I think above ERROR should not be shown if they use supported [type](https://github.com/elastic/support-diagnostics#diagnostic-types).

**Comment by pickypg** [comment]
This appears to be a longstanding bug and `logstash-api` appears to break that `type`:

https://github.com/elastic/support-diagnostics/blob/41edd4d8ea4d40aa68fde862966733f3a8044f40/src/main/java/co/elastic/support/diagnostics/commands/RunLogstashQueries.java#L103-L106

It should be calling out `Constants.logstashApi` and disabling system calls without throwing the exception.
